# Generated by Django 2.1.2 on 2018-10-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='entity_ct',
            field=models.ForeignKey(blank=True, help_text='Limit this Attribute to only apply to entities of this ContentType', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eav_attributes', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='entity_id',
            field=models.IntegerField(blank=True, help_text='Further limit this Attribute to only apply to the entity with this PK', null=True),
        ),
    ]
