# Generated by Django 2.1.2 on 2018-11-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0002_auto_20181029_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='extra_data',
            field=models.CharField(blank=True, help_text='Extra data for this attribute', max_length=256, null=True, verbose_name='Extra data'),
        ),
    ]
