# Generated by Django 2.2 on 2019-05-10 14:07

import django.contrib.gis.db.models.fields
from django.db import migrations
import eav.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0003_attribute_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='value_area',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='value',
            name='value_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='datatype',
            field=eav.fields.EavDatatypeField(choices=[('text', 'Text'), ('date', 'Date'), ('float', 'Float'), ('int', 'Integer'), ('bool', 'True / False'), ('object', 'Django Object'), ('enum', 'Multiple Choice'), ('point', 'Coordinates'), ('area', 'Area')], max_length=6, verbose_name='Data Type'),
        ),
    ]
