# Generated by Django 2.2.6 on 2019-10-12 18:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0004_add_postgis_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Extra data for this attribute, as JSON', null=True, verbose_name='Extra data'),
        ),
    ]
