# Generated by Django 2.2.6 on 2019-10-12 21:24

from django.db import migrations
import eav.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0005_extra_data_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=eav.fields.EavSlugField(help_text='Short attribute label. Does not have to be unique.', verbose_name='Slug'),
        ),
    ]
