# Generated by Django 2.2.6 on 2019-10-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('eav', '0006_auto_20191012_2124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('slug', 'entity_ct', 'entity_id')},
        ),
    ]
