# Generated by Django 2.2.6 on 2019-10-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0007_auto_20191012_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='entity_id',
        ),
        migrations.AddField(
            model_name='value',
            name='entity_uuid',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
