# Generated by Django 2.2.6 on 2019-10-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0008_auto_20191027_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='entity_uuid',
            new_name='entity_id',
        ),
    ]
