# Generated by Django 2.2.6 on 2019-10-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0010_value_generic_value_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='generic_value_id',
        ),
    ]
