# Generated by Django 2.2.6 on 2019-10-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0011_remove_value_generic_value_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='generic_value_uuid',
            new_name='generic_value_id',
        ),
    ]
